# Generated by Django 3.2.6 on 2021-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name': 'jogador', 'verbose_name_plural': 'jogadores'},
        ),
        migrations.AlterField(
            model_name='jogador',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
