# Generated by Django 3.2.6 on 2021-10-04 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'cidade', 'verbose_name_plural': 'cidades'},
        ),
        migrations.AddField(
            model_name='loja',
            name='ativo',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='item',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, to='bot.item'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='loja',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, to='bot.loja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='preco_sugerido',
            field=models.FloatField(max_length=100, verbose_name='Preço Sugerido'),
        ),
    ]
