# Generated by Django 3.2.6 on 2021-08-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personagem',
            options={'verbose_name': 'personagem', 'verbose_name_plural': 'personagens'},
        ),
        migrations.AddField(
            model_name='personagem',
            name='ativo',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='tipo',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
