# Generated by Django 3.2.6 on 2021-10-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='caixa',
            field=models.FloatField(default=0, max_length=100, verbose_name='Caixa'),
            preserve_default=False,
        ),
    ]
