# Generated by Django 3.2.6 on 2021-10-17 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estilovida',
            options={'verbose_name': 'estilovida', 'verbose_name_plural': 'estilosdevida'},
        ),
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 19, 39, 36, 973917)),
        ),
    ]
