# Generated by Django 3.2.6 on 2021-10-14 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 11, 22, 21, 500461)),
        ),
        migrations.AlterField(
            model_name='historico',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
