# Generated by Django 3.2.6 on 2021-09-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='nome_cidade',
            new_name='nome',
        ),
    ]
