# Generated by Django 3.2.6 on 2021-09-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_nome_cidade_cidade_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.item')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.personagem')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
            },
        ),
        migrations.AddField(
            model_name='personagem',
            name='inventario',
            field=models.ManyToManyField(through='bot.ItemJogador', to='bot.Item'),
        ),
    ]
