# Generated by Django 3.2.6 on 2021-10-14 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20211014_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 12, 11, 47, 106962)),
        ),
        migrations.AlterField(
            model_name='historico',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.loja'),
        ),
    ]
