# Generated by Django 3.2.6 on 2021-10-18 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20211017_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastossemanais',
            options={'verbose_name': 'gastossemanais', 'verbose_name_plural': 'gastossemanais'},
        ),
        migrations.AlterField(
            model_name='gastossemanais',
            name='tipo',
            field=models.CharField(choices=[(None, '<selecione>'), ('alimentos', 'Alimentos'), ('transporte', 'Transporte'), ('academico', 'Acadêmico'), ('agricultura', 'Agricultura'), ('casa', 'Casa'), ('equipamento', 'Equipamento'), ('luxo', 'Luxo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 21, 51, 3, 284760)),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe',
            field=models.CharField(choices=[(None, '<selecione>'), ('mago', 'Mago'), ('bruxo', 'Bruxo'), ('feiticeiro', 'Feiticeiro'), ('barbaro', 'Bárbaro'), ('bardo', 'Bardo'), ('cacador', 'Caçador'), ('cavaleiro', 'Cavaleiro'), ('clerigo', 'Clérigo'), ('druida', 'Druída'), ('guerreiro', 'Guerreiro'), ('inventor', 'Inventor'), ('ladino', 'Ladino'), ('lutador', 'Lutador'), ('nobre', 'Nobre'), ('paladino', 'Paladino')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='raca',
            field=models.CharField(choices=[(None, '<selecione>'), ('humano', 'Humano'), ('anão', 'Anão'), ('dahllan', 'Dahllan'), ('elfo', 'Elfo'), ('goblin', 'Goblin'), ('lefou', 'Lefou'), ('minotauro', 'Minotauro'), ('qareen', 'Qareen'), ('golem', 'Golem'), ('hynne', 'Hynne'), ('kliren', 'Kliren'), ('medusa', 'Medusa'), ('osteon', 'Osteon'), ('sereia/tritao', 'Sereia/Tritão'), ('silfide', 'Silfide'), ('aggelos', 'Aggelos'), ('sufulre', 'Sufulre'), ('trog', 'Trog')], max_length=100, verbose_name='Raça'),
        ),
    ]
