# Generated by Django 3.2.6 on 2021-10-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20211003_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='item',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.item'),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.UniqueConstraint(fields=('loja', 'item'), name='unique constraints'),
        ),
    ]
