# Generated by Django 3.2.6 on 2021-10-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20211008_1539'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itempersonagem',
            constraint=models.UniqueConstraint(fields=('personagem', 'item'), name='itempersonagem_constraint'),
        ),
    ]
