# Generated by Django 3.2.6 on 2021-09-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210904_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.personagem')),
            ],
        ),
    ]
