# Generated by Django 3.2.6 on 2021-09-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210929_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemJogador',
            new_name='ItemPersonagem',
        ),
    ]
