# Generated by Django 3.2.6 on 2021-10-14 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20211014_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 12, 39, 27, 408327)),
        ),
        migrations.AlterField(
            model_name='historico',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
