# Generated by Django 3.2.6 on 2021-09-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_loja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loja',
            options={'verbose_name': 'loja', 'verbose_name_plural': 'lojas'},
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Loja'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.personagem', verbose_name='Responsável'),
        ),
    ]
