# Generated by Django 3.2.6 on 2021-09-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='governante',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
