# Generated by Django 3.2.6 on 2021-09-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_cidade_governante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='ativo',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
