# Generated by Django 3.2.6 on 2021-09-30 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210930_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempersonagem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itempersonagem',
            old_name='personagem_id',
            new_name='personagem',
        ),
    ]
